"""tags, templates, versions, links, trash, manual order, starred folders

Revision ID: ad276df62543
Revises: 908d2bfad2dd
Create Date: 2026-10-05 13:54:20.123665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad276df62543'
down_revision = '908d2bfad2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('name_key', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'name_key', name=op.f('uq_tags_user_id'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('templates',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_user_id'), ['user_id'], unique=False)

    op.create_table('note_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('target_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['notes.id'], name=op.f('fk_note_links_source_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['notes.id'], name=op.f('fk_note_links_target_id_notes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_note_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_links'))
    )
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_links_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_links_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_links_target_key'), ['target_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_links_user_id'), ['user_id'], unique=False)

    op.create_table('note_tags',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_tags_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_note_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id', name=op.f('pk_note_tags'))
    )
    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('note_versions',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_versions_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_versions'))
    )
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_versions_note_id'), ['note_id'], unique=False)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('trashed_with', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_folders_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_trashed_with'), ['trashed_with'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('trashed_with', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_trashed_with'), ['trashed_with'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_trashed_with'))
        batch_op.drop_index(batch_op.f('ix_notes_deleted_at'))
        batch_op.drop_column('trashed_with')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('position')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_trashed_with'))
        batch_op.drop_index(batch_op.f('ix_folders_deleted_at'))
        batch_op.drop_column('trashed_with')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_starred')

    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_versions_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_versions_created_at'))

    op.drop_table('note_versions')
    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_tags_tag_id'))

    op.drop_table('note_tags')
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_note_links_target_key'))
        batch_op.drop_index(batch_op.f('ix_note_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_note_links_source_id'))

    op.drop_table('note_links')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_user_id'))

    op.drop_table('templates')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))

    op.drop_table('tags')
    # ### end Alembic commands ###
